---
title: "HCPF slides"
output: html_document
date: "2023-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
{
	library(here)
  library(tidyverse) 
  library(readxl)
	library(ggrepel)
	library(ggtext)
	library(showtext)
}

FONT <- "Lato"
showtext_auto()
sysfonts::font_add_google("Lato")

```  

```{r attr_data}
path <- readxl::read_excel(here("reports_hcpf_pres_march2023/hcpf_attr.xlsx"))

attr <- path %>% 
	select(-Obs) 

attr2 <- attr %>% 
	pivot_longer(cols = -flag,
											names_to = "month",
											values_to = "n"
											)  %>% 
	mutate(flag = factor(flag,
													levels = c(0,1),
													labels = c("Non-ISP",
																		 "ISP"))) %>% 
	mutate(month = stringr::str_replace_all(month, "_","")) %>% 
	group_by(flag) %>% 
	mutate(row = row_number()) %>% 
	mutate(month = lubridate::dmy(month)) %>% 
	mutate(x_txt = format(month, format = "%b '%y")) %>% 
	# mutate(x_text = case_when(
	# 	row %% 3 == 0 ~ format(month, format = "%b %Y"))) %>% 
	# add label at max 
	mutate(label0 = if_else(month == max(month), n, NA_real_)) %>% 
	mutate(label0 = scales::comma(label0)) %>% 
	mutate(label_max = if_else(!is.na(label0), 
														 glue::glue("{flag}\n(n={label0})"),
														 NA_character_)) %>% 

	ungroup()

```  

```{r attr_plot}
# range n: min=12092 max=1203140  
library(ggsci)

theme_set(theme_minimal(base_family = "Lato"))

theme_update(
  # Axes labels are grey, angled for x, and give margin for readability
  axis.text.x = element_text(color = "grey40", 
  													 angle = 45,
  													 margin = margin(t=15)),
  axis.text.y = element_text(color = "grey40"),
  # ticks light grey
  axis.ticks = element_line(color = "grey91", size = .5),
  # Remove the grid lines 
  panel.grid = element_blank(),
  # Customize margin values (top, right, bottom, left)
  plot.margin = margin(20, 10, 20, 10),
  # Use a light grey color for the background of both the plot and the panel
  plot.background = element_rect(fill = "grey98", color = "grey98"),
  panel.background = element_rect(fill = "grey98", color = "grey98"),
  # Customize title appearence
  plot.title = element_text(
    color = "grey10", 
    size = 28, 
    face = "bold",
    margin = margin(t = 15)
  ),
  # Customize subtitle appearence
  plot.subtitle = element_markdown(
    color = "grey30", 
    size = 16,
    lineheight = 1.35,
    margin = margin(t = 15, b = 40)
  ),
  # Title and caption are going to be aligned
  plot.title.position = "plot",
  plot.caption.position = "plot",
  plot.caption = element_text(
    color = "grey30", 
    size = 13,
    lineheight = 1.2, 
    hjust = 0,
    margin = margin(t = 40) # Large margin on the top of the caption.
  ),
  # Remove legend
  legend.position = "none"
)

labs <- list(
	x = "Month",
	y = "Unique Members (n)"
)

attr_plt0 <- ggplot(
	attr2,
	aes(row, n, group = flag)
	)+
	# vertical gridlines
	geom_vline(
		xintercept = seq(1,36,by = 3),
		color = "grey91",
		size = .6
	)+
	# dotted line for March 2020: 
	geom_vline(
		aes(xintercept = 9),
		color = "grey40",
		linetype = "dotted",
		size = .8
	  )+
	# horizontal gridlines
	geom_segment(
		data = tibble(y = seq(100000, 1400000, by = 100000), 
									x1 = 1, x2 = 36),
		aes(x=x1, xend = x2, y = y, yend = y),
		inherit.aes = FALSE,
		color = "grey91",
		size = .6
	)+
	# data points lines
	geom_line(
		aes(color = flag))

x_labels <- attr2 %>%
	select(row, x_txt) %>% 
	filter(row %%3 == 0)

attr_plt <- attr_plt0 + 
	# add the March text annotation 
	annotate(
	  "text", x = 9, y = 1350000,
	  label = "March\n2020",
	  family = "Lato",
  	size = 4,
  	color = "grey20",
  	hjust = 1.1,
	  lineheight = .7
  	) + 
	# add values at the end of the graph, without grid lines
	geom_text_repel(
		aes(color = flag,
				label = label_max),
		family = "Lato",
		fontface = "bold",
		size = 4,
		direction = "y",
		xlim = c(36.8, NA),
		hjust = 0,
		segment.size = .7,
		segment.alpha = .5, 
		segment.linetype = "dotted",
		box.padding = .4,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20,
		lineheight = .7
	) + 
	coord_cartesian(
		clip = "off",
		ylim = c(100000,1400000)
	)+
	scale_x_continuous(
		expand = c(0,0),
		limits = c(1,50),
		breaks = x_labels$row,
		labels = x_labels$x_txt
	)+
	# scale_x_continuous(
	# 	expand = c(0,0),
	# 	limits = c(1,50),
	# 	breaks = seq(1,36, by = 3)
	# )+
	scale_y_continuous(
		labels = scales::comma,
		expand = c(0,0),
		breaks = seq(100000,1400000, by = 100000)
		)+
	labs(
		y = labs$y,
		x = labs$x
	)+
	scale_color_jama()

attr_plt

```

