---
title: "HCPF slides"
output: html_document
date: "2023-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
{
	library(here)
  library(tidyverse) 
  library(readxl)
	library(ggrepel)
	library(ggtext)
	library(showtext)
	library(ragg)
	library(ggsci)
}

FONT <- "Lato"
showtext_auto()
sysfonts::font_add_google("Lato")

# import theme code: 
source(here("code/plots/hcpf_slides_plot_theme.R"))

```  

```{r get} 

# Unique Attributed members 01Jul2019-01Jul2022
attr0 <- readxl::read_excel(here("reports_hcpf_pres_march2023/hcpf_attr.xlsx"))

# Change in member attr relative to March 2020: 
rel0 <- read_excel(here("reports_hcpf_pres_march2023/hcpf_attr.xlsx"), 
  sheet = "relative_change_t") %>% 
	# to use the same function as attr, flag has to be numeric
	mutate(flag = if_else(flag == "ISP", 1, 0))
```


```{r attr_prep}

fn_prep <- function(df, df2){
	
	df2 <- df %>% 
		select(-Obs) %>% 
		pivot_longer(cols = -flag,
								 names_to = "month",
								 values_to = "n"
								 )  %>% 
		mutate(flag = factor(flag,
												 levels = c(0,1),
												 labels = c("Non-ISP","ISP"))) %>% 
	  mutate(month = stringr::str_replace_all(month, "_","")) %>% 
	  group_by(flag) %>% 
	  mutate(row = as.numeric(row_number())) %>% 
		
		# make month into date var, then extract month, year, q for grouping
	  mutate(month = lubridate::dmy(month)) %>% 
		mutate(month_abbrev = format(month, format = "%b")) %>% 
	  mutate(year  = format(month, format = "%Y")) %>% 
	  mutate(qrtr = quarter(month, with_year = FALSE)) %>% 
		
	  # add label for max at end of line graph 
	  mutate(label0 = if_else(month == max(month), n, NA_real_)) %>% 
	  mutate(label0 = scales::comma(label0)) %>% 
	  mutate(label_max = if_else(!is.na(label0), 
	  													 glue::glue("{flag}\n(n={label0})"),
	  													 NA_character_)) %>% 
		ungroup() %>% 
		select(-label0) %>% 
		
		# create x_label col indicator to subset outside function
		group_by(year, qrtr) %>% 
	  mutate(q_beg = ifelse(row == min(row), 1, 0)) %>%
		ungroup() %>% 
	  group_by(year) %>% 
	  mutate(
	  	x_txt = case_when(
	  		row == min(row) ~ format(month, format = "%b\n%Y"),
	  		TRUE ~ month_abbrev)) %>% 
	  ungroup() 
	
	return(df2)

}

attr <- fn_prep(attr0, attr)

# rel has to be split first before using function: 
rel_n0  <- rel0 %>% 
	filter(delta == "n_diff") %>%
	select(-delta) 

rel_pct0 <- rel0 %>% 
	filter(delta == "pct_diff") %>%
	select(-delta) 

rel_n <- fn_prep(rel_n0, rel_n)
rel_pct <- fn_prep(rel_pct0, rel_pct)

# function to create and subset the x_labels
fn_x_labels <- function(df_in){
	
	# make final: 
	final <- c(row = 36,
					 x_txt2 = "Jun")
	
	out <- df_in %>% 
		filter(q_beg == 1) %>% 
		select(row, x_txt) %>% 
		rbind(final)
	
	return(out)
}

attr_xlabs  <- fn_x_labels(attr)
rel_n_xlabs <- fn_x_labels(rel_n)
rel_pct_xlabs <- fn_x_labels(rel_pct)

rm(rel_n0, attr0, rel_pct0, rel0)

```  

```{r attr_plot}
# range n: min=12092 max=1203140  

fn_plot <- function(dat, ylo, yhi, yby){
	
	plot <- ggplot(
		dat,
		aes(row, n, group = flag)
	 )+
	# vertical gridlines
	geom_vline(
		xintercept = seq(1,36,by = 3),
		color = "grey91",
		size = .6
	)+
	# dotted line for March 2020: 
	geom_vline(
		aes(xintercept = 9),
		color = "grey40",
		linetype = "dotted",
		size = .8
	  )+
	# horizontal gridlines
	geom_segment(
		data = tibble(y = seq(ylo, yhi, by = yby), 
									x1 = 1, x2 = 36),
		aes(x=x1, xend = x2, y = y, yend = y),
		inherit.aes = FALSE,
		color = "grey91",
		size = .6
	)+
	# data points lines
	geom_line(
		aes(color = flag))+
		# add the March text annotation 
	annotate(
	  "text", x = 9, y = 1305000,
	  label = "March\n2020",
	  family = "Lato",
  	size = 4,
  	color = "grey20",
  	hjust = 1.1,
	  lineheight = .7
  	) + 
	# add values at the end of the graph, without grid lines
	geom_text_repel(
		aes(color = flag,
				label = label_max),
		family = "Lato",
		fontface = "bold",
		size = 4,
		direction = "y",
		xlim = c(36.8, NA),
		hjust = 0,
		segment.size = .7,
		segment.alpha = .5, 
		segment.linetype = "dotted",
		box.padding = .4,
    segment.curvature = -0.1,
    segment.ncp = 3,
    segment.angle = 20,
		lineheight = .7
	) + 
	coord_cartesian(
		clip = "off",
		ylim = c(ylo,yhi)
	)+
	scale_x_continuous(
		expand = c(0,0),
		limits = c(1,45),
		breaks = x_labels$row,
		labels = x_labels$x_txt2
	)+
	scale_y_continuous(
		labels = scales::comma,
		expand = c(0,0),
		breaks = seq(ylo,yhi, by = yby)
		)+
	labs(
		y = "",
		x = ""
	)+
	scale_color_jama()
	
	return(plot)
}

attr_plot <- fn_plot(attr, 100000, 1400000, 100000)

# geom_segment seq attr seq(100000, 1400000, by = 100000), 
attr_plt0 <- ggplot(
	attr,
	aes(row, n, group = flag)
	)+
	# vertical gridlines
	geom_vline(
		xintercept = seq(1,36,by = 3),
		color = "grey91",
		size = .6
	)+
	# dotted line for March 2020: 
	geom_vline(
		aes(xintercept = 9),
		color = "grey40",
		linetype = "dotted",
		size = .8
	  )+
	# horizontal gridlines
	geom_segment(
		data = tibble(y = seq(100000, 1400000, by = 100000), 
									x1 = 1, x2 = 36),
		aes(x=x1, xend = x2, y = y, yend = y),
		inherit.aes = FALSE,
		color = "grey91",
		size = .6
	)+
	# data points lines
	geom_line(
		aes(color = flag))


attr_plt <- attr_plt0 + 
	

attr_plt

```  

```{r rel_change_get}

#
```

