---
title: "HCPF slides"
output: html_document
date: "2023-02-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
											#dev.args = list(png = list(type = "cairo")))
{
	library(here)
  library(tidyverse) 
  library(readxl)
	library(ggrepel)
	library(ggtext)
	library(showtext)
	library(ggsci)
}

FONT <- "Lato"
showtext_auto()
sysfonts::font_add_google("Lato")

# import theme code: 
source(here("code/plots/plot_theme.R"))

# import function files: 
source(here("code/plots/fn_plot.R"))  
source(here("code/plots/fn_plot_q.R"))
source(here("code/plots/fn_prep_data.R"))  
source(here("code/plots/fn_x_labels.R"))  

```  

Child Files:  

 - `fn_prep_data.R` has processing steps for attr & rel, fn_prep_data2 for q 
 - `fn_plot.R` has plotting function  
 - `fn_x_labels.R` creates the labels for x axis    
 - `plot_theme.R` has plot theme  info  


```{r tele_p}
# telehealth percentages 
tele0 <- read_excel(here("reports_hcpf_pres/hcpf_telehealth.xlsx"), 
    sheet = "pct_tele", 
    # have to specify col types was bringing in first ones as char?!
    col_types = c("numeric", "text", "text", 
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric", 
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric",
    							"numeric", "numeric", "numeric", "numeric", "numeric", "numeric")
    ) %>% 
	rename(flag = ISP) %>% 
	# only need to plot pct per Mark
	filter(metric == "pct") %>%   
	# I had some totals in below for MG ; remove them
	filter(!is.na(flag)) %>% 
	select(-metric) %>% 
	# flag needs to be 0, 1 for fn_prep for now: 
	mutate(flag = if_else(flag == "ISP", 1, 0)) 
	

tele <- fn_prep_data(tele0, tele)
tele$n[is.na(tele$n)] <- 0


# get formatted pct in the n column instead of decimals
tele1 <- tele %>% 
	# copy the n var so you can use that for y axis, the pct for labels
	mutate(pct = paste0(n)) %>% 
	mutate(pct = as.numeric(n)) %>% 
	# remove first label_max from before: 
	select(-label_max) %>% 
	# round to two digits for both n and pct
	mutate_at(vars(n,pct), ~ round(.*100, digits = 0)) %>% 
	group_by(flag) %>% 
	mutate(label0 = if_else(month == max(month), pct, NA_real_)) %>% 
	mutate(label_max = if_else(!is.na(label0), 
															 glue::glue("{flag}: {label0}%"),
															 NA_character_)) %>% 
	ungroup() 


tele_xlabs  <- fn_x_labels(tele1)  

# save tele_RData
save(tele1,
		 tele_xlabs,
		 file = here::here("code/plots/tele_dfs.RData")) 

tele_plot <- fn_plot(
	tele1, 
	n,
	0, 
	80, 
	10, 
	xlabels = tele_xlabs,
	y_annot = 75,
	"Percent",
	"Month",
	"Percentage of PCMPs Providing Telehealth Services",
	"FY 2019-2022",
	"Data extracted on 03-01-2023\nAll months in timeframe are represented in the plot; for readability, only quarter and yearly start months have been labeled")

tele_plot

# save plot 
ggsave(here("reports_hcpf_pres/plot_tele_pct.svg"),
						width = 10, height = 5)


```


```{r attr_qrtrly}
# prep data with function fn_prep_data2 (imports and preps)
q <- fn_prep_q()	

#fn_plot <- function(dat, yvar, ylo, yhi, yby, xlabels, 
#										labx, laby, 
#										title, subtitle, caption) 

q_xlabs <- q %>% 
	select(row, x_txt)

# save q_RData
save(q,
		 q_xlabs,
		 file = here::here("code/plots/qrtr_dfs.RData")) 


# range(q$n	) -- [1]  128584 1214935  

#NB fix later the labels are assigned opposite way - works this way: (labx, laby)
q_plot <- fn_plot_q(q,
										q_xlabs,
										labx = "Members (n)",
									  laby = "Quarter",
									  title = "Attributed Members by Quarter",
									  subtitle = "FY 2019-2022",
									  caption = "Data extracted 03/01/2023")

q_plot

# save plot 
ggsave(here("reports_hcpf_pres/plot_attr_qrtr.svg"),
						width = 10, height = 5)

```  

```{r attr}

# Unique Attributed members 01Jul2019-01Jul2022
attr0 <- readxl::read_excel(here("reports_hcpf_pres/hcpf_attr.xlsx"))

# prep data with function
attr <- fn_prep_data(attr0, attr)

# get attr_xlabs
attr_xlabs  <- fn_x_labels(attr)

# save attr_RData
save(attr,
		 attr_xlabs,
		 file = here::here("code/plots/attr_dfs.RData")) 

# read in option:
load(here("code/plots/attr_dfs.RData"))

# Attr plot function
attr_plot <- fn_plot(
	attr, 
	n,
	0, 
	1400000, 
	100000, 
	xlabels = attr_xlabs,
	y_annot = 1305000,
	"Members (n)",
	"Month",
	"Monthly Member Attribution",
	"July 1, 2019 through June 30, 2022",
	"Data extracted on 03-01-2023\nAll months in timeframe are represented in the plot; for readability, only quarter and yearly start months have been labeled")
attr_plot
# save attr plot 
ggsave(here("reports_hcpf_pres/plot_attr.svg"), 
			 width = 10, height = 5)
# try shorter?
# ggsave("attr_plot.svg", width = 10, height = 6)

```


```{r rel} 

# Import Data / Change in member attr relative to March 2020: 
rel0 <- read_excel(here("reports_hcpf_pres/hcpf_attr.xlsx"), 
  sheet = "relative_change_t") %>% 
	# to use the same function as attr, flag has to be numeric
	mutate(flag = if_else(flag == "ISP", 1, 0))

# rel has to be split first before using function: 
rel_n0  <- rel0 %>% 
	filter(delta == "n_diff") %>%
	select(-delta) 

rel_pct0 <- rel0 %>% 
	filter(delta == "pct_diff") %>%
	select(-delta) 

rel_n <- fn_prep_data(rel_n0,   rel_n  )
rel_p <- fn_prep_data(rel_pct0, rel_pct)

# needs replace the n with pct and add percent sign:
rel_p <- rel_p %>% 
	rename(p = n) %>% 
	mutate(label_max = str_replace_all(label_max, c("\\(n" = "\\(pct",
																									"\\)" = "\\%\\)")))
# only need it for 1
rel_p_xlabs <- fn_x_labels(rel_p)

rm(rel_n0, attr0, rel_pct0, rel0)

save(rel_n,
		 rel_p,
		 rel_p_xlabs,
		 file = here::here("code/plots/rel_dfs.RData"))

# range(rel_p$p) 0, 34

rel_plot <- fn_plot(
	rel_p, 
	p,
	0, 
	35, 
	5, 
	xlabels = rel_p_xlabs,
	y_annot = 33,
	"Percent",
	"Month",
	"Attributed Members: Percent Change Relative to March 2020",
	"FY 2019-2022",
	"Data extracted on 03-01-2023\nAll months in timeframe are represented in the plot; for readability, only quarter and yearly start months have been labeled")

rel_plot

ggsave(here("reports_hcpf_pres/plot_rel_change.svg"), 
						width = 10, height = 5)

```




